FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -buildvcs=false -o /out/user-service ./cmd/user-service

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/user-service /app/user-service

EXPOSE 50051

CMD ["/app/user-service"]