FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -buildvcs=false -o /out/storage-controller ./cmd/storage-controller
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/storage-controller /app/storage-controller
EXPOSE 50060
CMD ["/app/storage-controller"]
