FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -buildvcs=false -o /out/notification-service ./cmd/notification-service
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/notification-service /app/notification-service
EXPOSE 50057
CMD ["/app/notification-service"]
