FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -buildvcs=false -o /out/property-service ./cmd/property-service

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/property-service /app/property-service

EXPOSE 50052

CMD ["/app/property-service"]