FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -buildvcs=false -o /out/document-service ./cmd/document-service
FROM alpine:3.20
WORKDIR /app
COPY --from=builder /out/document-service /app/document-service
EXPOSE 50058
CMD ["/app/document-service"]
