FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -buildvcs=false -o /out/matching-service ./cmd/matching-service

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /out/matching-service /app/matching-service

EXPOSE 50056

CMD ["/app/matching-service"]
