apiVersion: v1
kind: Namespace
metadata:
  name: rentrelay

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rentrelay-config
  namespace: rentrelay
data:
  MONGO_DATABASE: "rentrelay"
  HEARTBEAT_INTERVAL_SEC: "5"
