apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-worker-2
  namespace: rentrelay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-worker-2
  template:
    metadata:
      labels:
        app: storage-worker-2
    spec:
      containers:
        - name: storage-worker
          image: rentrelay/storage-worker:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50061
          env:
            - name: CONTROLLER_ADDR
              value: "storage-controller:50060"
            - name: GRPC_PORT
              value: "50061"
            - name: HEARTBEAT_INTERVAL_SEC
              value: "5"
            - name: WORKER_ID
              value: "storage-worker-2"
            - name: WORKER_ADDRESS
              value: "storage-worker-2:50061"
            - name: SHARD_START
              value: "128"
            - name: SHARD_END
              value: "191"

---
apiVersion: v1
kind: Service
metadata:
  name: storage-worker-2
  namespace: rentrelay
spec:
  selector:
    app: storage-worker-2
  ports:
    - name: grpc
      port: 50061
      targetPort: 50061
